name: sports
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.8.2
  duration_picker: ^1.1.1
  file_picker: ^5.3.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.0
  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  go_router: ^9.0.0
  google_sign_in: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.6
  image_cropper: ^5.0.0
  json_annotation: ^4.8.1
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
